Repository creatorsgarten/hacktoberfest-museum, pull requests merged in 2022-10, with the labels that each got.

#1 ✨ add /gallery page
  .vscode/settings.json
  package-lock.json
  package.json
  public/assets/gallery-background.jpg
  public/assets/image-1.png
  public/assets/image-2.png
  public/assets/image-3.png
  src/components/Card.svelte
  src/enums/founders.enum.ts
  src/enums/topics.enum.ts
  src/pages/gallery.astro
  src/style/card-theme.css
  src/style/root.css
  src/style/typography.css
  src/types/card.interface.ts
  tailwind.config.cjs
  yarn.lock
Labels: READY FOR REVIEW

#3 feat(site): use hacktoberfest favicon
  public/favicon.svg
Labels: hacktoberfest-accepted

#5 docs: :bookmark: add tagging rule to CONTRIBUTING.MD
  CONTRIBUTING.MD
Labels: documentation, 🚀 READY FOR REVIEW

#6 ✨add mukpakpak to the museum
  public/images/mukpakpak.jpeg
  src/enums/founders.enum.ts
  src/enums/topics.enum.ts
  src/pages/index.astro
Labels: 🚀 READY FOR REVIEW, hacktoberfest-accepted, The new entry 💫

#9 docs: :memo: add application form linkout to README and PR template
  PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation, 🚀 READY FOR REVIEW

#7 💄 change grid breakpoint to `xl` rather than `2xl`
  src/pages/index.astro
Labels: Enhancement 🛠, 🚀 READY FOR REVIEW

#12 fix: add breakpoint to padding for better card view
  src/pages/index.astro
Labels: Enhancement 🛠, 🚀 READY FOR REVIEW, hacktoberfest-accepted

#14 Added KNACKSAT2 TGPS
  public/images/TGPSPro.png
  src/enums/founders.enum.ts
  src/enums/topics.enum.ts
  src/pages/index.astro
Labels: hacktoberfest-accepted, The new entry 💫

#13 feat: separate entries to folder
  astro.config.mjs
  package-lock.json
  package.json
  src/entries/awesome-cheab-quotes.ts
  src/entries/coffee-to-code.ts
  src/entries/deploydemai-today.ts
  src/entries/dumb-questions.ts
  src/entries/knacksat2-tgps-sattlelite-hardware.ts
  src/entries/mukpakpak.ts
  src/entries/nunmun.ts
  src/entries/react-useless-hooks.ts
  src/entries/torpleng.ts
  src/entries/watasalim.ts
  src/pages/index.astro
  src/types/entry.interface.ts
  yarn.lock
Labels: Enhancement 🛠, help wanted, 🚀 READY FOR REVIEW, hacktoberfest-accepted

#16 fix: hide scrollbar on windows
  src/style/root.css
Labels: Enhancement 🛠, 🚀 READY FOR REVIEW

#18 chore: force everyone to use pnpm because it's better
  .npmrc
  CONTRIBUTING.MD
  package-lock.json
  package.json
  pnpm-lock.yaml
  yarn.lock
Labels: Enhancement 🛠, 🚀 READY FOR REVIEW

#17 [Feat] Filter Search
  src/components/ProjectEntrySearchCards.svelte
  src/components/SeachInput.svelte
  src/pages/index.astro
Labels: Enhancement 🛠, 🚀 READY FOR REVIEW

#19 Add Playwright test
  .github/workflows/playwright.yml
  .gitignore
  .vscode/extensions.json
  package.json
  playwright.config.ts
  pnpm-lock.yaml
  src/components/SeachInput.svelte
  src/pages/index.astro
  tests/museum.spec.ts
  tsconfig.json
Labels: Enhancement 🛠

#25 feat: add typecheck and prettier check CI on Github Actions
  .github/workflows/code-style-check.yml
  package.json
  pnpm-lock.yaml
  src/components/Card.svelte
  src/enums/founders.enum.ts
  src/layouts/main.astro
  src/pages/markdown-page.md
  tsconfig.json
Labels: Enhancement 🛠

#27 chore: ignore other lockfiles
  .gitignore
Labels: Enhancement 🛠, 🚀 READY FOR REVIEW

#15 Change some name also button for univisal project.
  src/components/Card.svelte
  src/entries/knacksat2-tgps-sattlelite-hardware.ts
  src/enums/topics.enum.ts
Labels: Enhancement 🛠, 🚀 READY FOR REVIEW

#20 feat: added ProjectThemes enum
  README.md
  src/components/Card.svelte
  src/enums/themes.enum.ts
  src/types/card.interface.ts
Labels: Enhancement 🛠, 🚀 READY FOR REVIEW, hacktoberfest-accepted

#26 add tsuki repo
  src/entries/tsuki.ts
  src/enums/founders.enum.ts
  src/enums/topics.enum.ts
Labels: 🚀 READY FOR REVIEW, hacktoberfest-accepted, The new entry 💫

#30 Add my name to Pillars of Creation
  README.md
Labels: documentation, 🚀 READY FOR REVIEW

#32 feat(pillar): add Leomotors to Pillars of Creation
  README.md
Labels: 🚀 READY FOR REVIEW

#31 docs: :memo: update quick guide section to entries folder instead of …
  CONTRIBUTING.MD
Labels: documentation, 🚀 READY FOR REVIEW

#35 fix(home-page): Firefox Related CSS errors
  src/pages/index.astro
  src/style/root.css
Labels: Enhancement 🛠, hacktoberfest-accepted, The new entry 💫

#34 Added my self??????
  README.md
Labels: 🚀 READY FOR REVIEW

#36 fix: correct icons
  src/enums/themes.enum.ts
Labels: Enhancement 🛠, 🚀 READY FOR REVIEW

#37 chore(prettier): add lint staged husky precommit hooks
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
Labels: Enhancement 🛠

#40 refactor: type safe entries
  CONTRIBUTING.MD
  src/entries/awesome-cheab-quotes.ts
  src/entries/coffee-to-code.ts
  src/entries/cross-clipboard.ts
  src/entries/deploydemai-today.ts
  src/entries/dumb-questions.ts
  src/entries/knacksat2-tgps-sattlelite-hardware.ts
  src/entries/mukpakpak.ts
  src/entries/nunmun.ts
  src/entries/react-useless-hooks.ts
  src/entries/torpleng.ts
  src/entries/tsuki.ts
  src/entries/watasalim.ts
  src/enums/themes.enum.ts
Labels: Enhancement 🛠, 🚀 READY FOR REVIEW

#43 Add awesome-rickroll-videos
  public/images/rickroll.jpg
  src/entries/awesome-rickroll-videos.ts
  src/enums/topics.enum.ts
Labels: 🚀 READY FOR REVIEW, 🎄 weed requested, เอาไปเลยดวงใจนู๋ 💘

#44 Added EasyEDA
  src/entries/EasyEDA - PCB Design.ts
  src/enums/founders.enum.ts
  src/enums/topics.enum.ts
Labels: 🚀 READY FOR REVIEW
